# .github/workflows/nodejs-backend.yml

name: Backend CI

on:
  workflow_dispatch:     # manual trigger via the Actions UI or API :contentReference[oaicite:0]{index=0}
  push:
    branches:
      - master          # now runs on any push to the default branch :contentReference[oaicite:1]{index=1}

jobs:
  build-and-seed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3   # grab your code :contentReference[oaicite:2]{index=2}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: project/backend

      - name: Seed Database
        run: npm run seed
        working-directory: project/backend
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Start Server
        run: npm start
        working-directory: project/backend
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
